print ('Please enter the following:')
adjective_01 = input('Adjective: ')
animal_01 = input('Animal: ')
verb_01 = input('Verb: ')
exclamation_01 = input('Exclamation: ')
verb_02 = input('Verb: ')
verb_03 = input('Verb: ')
# The rest of these variables are for use with the continuation of the story to reach a full grade
adjective_02 = input('Adjective: ')
adjective_03 = input('Adjective: ')
animal_02 = input('Animal: ')
verb_04 = input('Verb: ')
exclamation_02 = input('Exclamation: ')
print()
print('Your story is:')
print()
print('The other day, I was really in trouble. It all started when I saw a very')
print(f'{adjective_01} {animal_01} {verb_01} down the hallway. "{exclamation_01.capitalize()}!" I yelled. But all')
print(f'I could think to do was to {verb_02} over and over. Miraculously,')
print(f'that caused it to stop, but not before it tried to {verb_03}')
print(f'right in front of my family. My {adjective_02} mother ran into the other room')
print(f'and grabbed a very {adjective_03} {animal_02}. When she brought it back into the room,')
print(f'it immeadiately started to {verb_04} towards the {animal_01}. An ultimate showdown had commenced.')
print(f'"{exclamation_02.capitalize()}!" we cheered, as we settled down to watch.')
print()
