print('Please enter the following information:')
first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone = input('Phone number: ')
job = input('Job title: ')
id_number = input('ID Number: ')
hair = input('Hair color: ')
eye = input('Eye color: ')
month = input('Month started: ')
training = input('Completed training: ')
print()
print('The ID Card is:')
print('----------------------------------------')
print(f'{last_name.upper()}, {first_name.capitalize()}')
print(job.title())
print(f'ID: {id_number}')
print()
print(email.lower())
print(phone)
print()
# print('Hair: %-*s Eyes: %s' % (13, hair.capitalize(), eye.capitalize() ))
# print('Month: %-*s Training: %s' % (12, month.capitalize(), training.capitalize() ))
print(f"Hair: {hair.capitalize():15} Eyes: {eye.capitalize()}")
print(f"Month: {month.capitalize():14} Training: {training.capitalize()}")
print('----------------------------------------')
print()
