color = input('Hi there! Would you mind telling me your favorite color?: ')
print ('That is awesome that your favorite color is ' + color + '!') 
print ('My favorite color happens to be red!')
book = input('If you do not mind me asking, what is your favorite book?: ')
print ('Woah!, ' + book + ', I have heard that is an awesome book!')
print ('My favorite book is Rhythm of War!')
print ('P.S. I am sorry that I am using so many exlamation marks...')
